# Generated by Django 5.2.7 on 2025-11-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CachingSystemApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocation",
            name="friends",
            field=models.ManyToManyField(
                blank=True, to="CachingSystemApp.userlocation"
            ),
        ),
    ]
